dev:
  entrypoint: "./entrypoint.sh"
  environment:
    - SSH_AUTH_SOCK=/ssh-agent
  image: gijsjan/webdev:1.1
  ports:
    - "3000:3000"
    - "4000:4000"
  volumes:
    - ..:/home/developer/marginal-scholarship-frontend
    - ../../hire-faceted-search:/home/developer/hire-faceted-search
    - ../../hire-forms-textarea:/home/developer/hire-forms-textarea
    - ../../hire-forms-select:/home/developer/hire-forms-select
    - ../../hire-forms-options:/home/developer/hire-forms-options
    - ../../hire-forms-select-combo:/home/developer/hire-forms-select-combo
    - ../../hire-forms-list-filter:/home/developer/hire-forms-list-filter
    - ./tmuxinator.yml:/home/developer/.tmuxinator/marginal-scholarship.yml
    - ./entrypoint.sh:/home/developer/entrypoint.sh
    - ~/.vimrc:/home/developer/.vimrc
    - ~/.ssh:/home/developer/.ssh
    - ${SSH_AUTH_SOCK}:/ssh-agent
