# ~/.tmuxinator/hire-forms.yml

name: marginal-scholarship
root: ~/marginal-scholarship-frontend
tmux_command: tmux -2
windows:
  - npm:
      layout: even-horizontal
      panes:
        - npm start
        - npm run watch
  - git:
      layout: even-horizontal
      panes:
        - git st
  - fs:
      layout: even-horizontal
      panes:
        - npm start
        - git st
      root: ~/hire-faceted-search
  - login:
      layout: even-horizontal
      panes:
        - npm start
        - git st
      root: ~/hire-login
  - textarea:
      layout: even-horizontal
      panes:
        - npm start
        - git st
      root: ~/hire-textarea
  - listfilter:
      layout: even-horizontal
      panes:
        - npm start
        - git st
      root: ~/hire-forms-list-filter
